--
--
-- Licensed Materials - Property of IBM
-- 5724X98 5724Y15 5655V82 5724X99 5724Y16 5655V89 5725B69 5655W88 5725C52 5655W90 5655Y31
-- Copyright IBM Corp. 1987, 2017 All Rights Reserved
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.
--
--


DROP INDEX SCENARIOSUITEELEMENT.SCE_INDEX;
DROP INDEX CHECKPOINTDATA.CHK_INDEX;

DROP TRIGGER STEPEXEC_TRIGGER;
DROP TRIGGER JOBINSTANCEDATA_TRIGGER;

DROP TABLE SCENARIOSUITEELEMENT;

DROP TABLE CHECKPOINTDATA;
DROP TABLE STEPSTATUS;
DROP TABLE JOBSTATUS;
DROP TABLE STEPEXECUTIONINSTANCEDATA;
DROP TABLE EXECUTIONINSTANCEDATA;
DROP TABLE JOBINSTANCEDATA;


CREATE TABLE SCENARIOSUITEELEMENT (
  ID 				NUMERIC(10, 0) IDENTITY NOT NULL,
  JOB_EXECUTION_ID 	NUMERIC(10, 0) NOT NULL,
  ELEMENT_ID 		VARCHAR(100) NOT NULL,
  ELEMENT_TYPE 		CHAR(1) NOT NULL,
  ELEMENT_CONTENT 	IMAGE NULL,
  CONSTRAINT RV_VALS_RT PRIMARY KEY (ID)
);


CREATE TABLE JOBINSTANCEDATA(
  jobinstanceid    	NUMERIC(10, 0) IDENTITY NOT NULL,
  name				VARCHAR(512) NULL, 
  apptag 			VARCHAR(512) NULL,
  CONSTRAINT JOBINST_PK PRIMARY KEY (jobinstanceid)
);

CREATE TABLE EXECUTIONINSTANCEDATA(
  jobexecid     NUMERIC(10, 0) IDENTITY NOT NULL, 
  jobinstanceid NUMERIC(10, 0),
  createtime  	DATETIME NULL,
  starttime  	DATETIME NULL,
  endtime   	DATETIME NULL,
  updatetime  	DATETIME NULL,
  parameters  	IMAGE NULL,
  batchstatus   VARCHAR(512) NULL,
  exitstatus    VARCHAR(512) NULL,
  CONSTRAINT JOBEXEC_PK PRIMARY KEY (jobexecid),
  CONSTRAINT JOBINST_JOBEXEC_FK FOREIGN KEY (jobinstanceid) REFERENCES JOBINSTANCEDATA (jobinstanceid)
);

CREATE TABLE STEPEXECUTIONINSTANCEDATA(
  stepexecid     	NUMERIC(10, 0) IDENTITY NOT NULL, 
  jobexecid      	NUMERIC(10, 0) NOT NULL, 
  batchstatus       VARCHAR(512) NULL,
  exitstatus      	VARCHAR(512) NULL,
  stepname      	VARCHAR(512) NULL,
  readcount         INTEGER NULL,
  writecount        INTEGER NULL,
  commitcount       INTEGER NULL,
  rollbackcount     INTEGER NULL,
  readskipcount     INTEGER NULL,
  processskipcount  INTEGER NULL,
  filtercount       INTEGER NULL,
  writeskipcount    INTEGER NULL,
  starttime         DATETIME NULL,
  endtime           DATETIME NULL,
  persistentdata    IMAGE NULL,
  CONSTRAINT STEPEXEC_PK PRIMARY KEY (stepexecid),
  CONSTRAINT JOBEXEC_STEPEXEC_FK FOREIGN KEY (jobexecid) REFERENCES EXECUTIONINSTANCEDATA (jobexecid)
);  
  
CREATE TABLE JOBSTATUS (
  id		NUMERIC(10, 0) NOT NULL,
  obj		IMAGE NULL,
  CONSTRAINT JOBSTATUS_PK PRIMARY KEY (id)
);

CREATE TABLE STEPSTATUS (
  id		NUMERIC(10, 0) NOT NULL,
  obj		IMAGE NULL,
  CONSTRAINT STEPSTATUS_PK PRIMARY KEY (id)
);

CREATE TABLE CHECKPOINTDATA (
  id		VARCHAR(512),
  obj		IMAGE NULL
);

CREATE INDEX SCE_INDEX ON SCENARIOSUITEELEMENT(JOB_EXECUTION_ID, ELEMENT_ID, ELEMENT_TYPE);
CREATE INDEX CHK_INDEX ON CHECKPOINTDATA(id);

CREATE TRIGGER JOBINSTANCEDATA_TRIGGER
ON JOBINSTANCEDATA 
FOR DELETE AS 
BEGIN 
    DELETE JOBSTATUS 
    FROM JOBSTATUS, deleted 
    WHERE deleted.jobinstanceid = JOBSTATUS.id
END;

CREATE TRIGGER STEPEXEC_TRIGGER
ON STEPEXECUTIONINSTANCEDATA 
FOR DELETE AS 
BEGIN 
    DELETE STEPSTATUS 
    FROM STEPSTATUS, deleted 
    WHERE deleted.stepexecid = STEPSTATUS.id
END;

