--
--
-- Licensed Materials - Property of IBM
-- 5724X98 5724Y15 5655V82 5724X99 5724Y16 5655V89 5725B69 5655W88 5725C52 5655W90 5655Y31
-- Copyright IBM Corp. 1987, 2017 All Rights Reserved
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.
--
--

DROP TABLE IF EXISTS SCENARIOSUITEELEMENT;
DROP TABLE IF EXISTS CHECKPOINTDATA;
DROP TABLE IF EXISTS STEPSTATUS;
DROP TABLE IF EXISTS JOBSTATUS;
DROP TABLE IF EXISTS STEPEXECUTIONINSTANCEDATA;
DROP TABLE IF EXISTS EXECUTIONINSTANCEDATA;
DROP TABLE IF EXISTS JOBINSTANCEDATA;


CREATE TABLE IF NOT EXISTS  SCENARIOSUITEELEMENT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  JOB_EXECUTION_ID BIGINT NOT NULL,
  ELEMENT_ID VARCHAR(100),
  ELEMENT_TYPE CHAR(1) NOT NULL,
  ELEMENT_CONTENT LONGBLOB,
  CONSTRAINT RV_VALS_RT PRIMARY KEY (ID)
)ENGINE=InnoDB;



CREATE TABLE IF NOT EXISTS JOBINSTANCEDATA(
  jobinstanceid   BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name    VARCHAR(512), 
  apptag VARCHAR(512)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS EXECUTIONINSTANCEDATA(
  jobexecid     BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  jobinstanceid BIGINT,
  createtime  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  starttime   TIMESTAMP NULL,
  endtime   TIMESTAMP NULL,
  updatetime  TIMESTAMP NULL,
  parameters  LONGBLOB,
  batchstatus   VARCHAR(512),
  exitstatus    VARCHAR(512),
  CONSTRAINT JOBINST_JOBEXEC_FK FOREIGN KEY (jobinstanceid) REFERENCES JOBINSTANCEDATA (jobinstanceid)
  )ENGINE=InnoDB;
  
CREATE TABLE IF NOT EXISTS STEPEXECUTIONINSTANCEDATA(
  stepexecid    BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  jobexecid BIGINT,
  batchstatus       VARCHAR(512),
  exitstatus      VARCHAR(512),
  stepname        VARCHAR(512),
  readcount         INT,
  writecount        INT,
  commitcount       INT,
  rollbackcount     INT,
  readskipcount     INT,
  processskipcount  INT,
  filtercount       INT,
  writeskipcount    INT,
  startTime           TIMESTAMP NULL,
  endTime             TIMESTAMP NULL,
  persistentData    LONGBLOB,
  CONSTRAINT JOBEXEC_STEPEXEC_FK FOREIGN KEY (jobexecid) REFERENCES EXECUTIONINSTANCEDATA (jobexecid)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS JOBSTATUS (
  id		BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  obj   LONGBLOB,
  CONSTRAINT JOBSTATUS_JOBINST_FK FOREIGN KEY (id) REFERENCES JOBINSTANCEDATA (jobinstanceid) ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS STEPSTATUS(
  id		BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
  obj   LONGBLOB,
  CONSTRAINT STEPSTATUS_STEPEXEC_FK FOREIGN KEY (id) REFERENCES STEPEXECUTIONINSTANCEDATA (stepexecid) ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS CHECKPOINTDATA(
  id		VARCHAR(512),
  obj		LONGBLOB
)ENGINE=InnoDB;

  

