--
--
-- Licensed Materials - Property of IBM
-- 5724X98 5724Y15 5655V82 5724X99 5724Y16 5655V89 5725B69 5655W88 5725C52 5655W90 5655Y31
-- Copyright IBM Corp. 1987, 2017 All Rights Reserved
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.
--
--


DROP SEQUENCE SCENARIOSUITEELEMENT_SEQ;
DROP SEQUENCE JOBINSTANCEDATA_SEQ;
DROP SEQUENCE EXECINSTANCEDATA_SEQ;
DROP SEQUENCE STEP_SEQ;



DROP TABLE SCENARIOSUITEELEMENT;

DROP TABLE CHECKPOINTDATA;
DROP TABLE STEPSTATUS;
DROP TABLE JOBSTATUS;
DROP TABLE STEPEXECUTIONINSTANCEDATA;
DROP TABLE EXECUTIONINSTANCEDATA;
DROP TABLE JOBINSTANCEDATA;

CREATE TABLE SCENARIOSUITEELEMENT (
  ID 				NUMBER(19,0) NOT NULL,
  JOB_EXECUTION_ID 	NUMBER(19,0) NOT NULL,
  ELEMENT_ID 		VARCHAR(100) NOT NULL,
  ELEMENT_TYPE 		CHAR(1) NOT NULL,
  ELEMENT_CONTENT 	BLOB,
  CONSTRAINT RV_VALS_RT PRIMARY KEY (ID),
  CONSTRAINT SSE_UNIQUE UNIQUE (JOB_EXECUTION_ID, ELEMENT_ID, ELEMENT_TYPE)
);

CREATE SEQUENCE SCENARIOSUITEELEMENT_SEQ
  START WITH 1
  INCREMENT BY 1
  NOMAXVALUE;

  
--
-- Job informmations schema
--

CREATE TABLE JOBINSTANCEDATA(
  jobinstanceid		NUMBER(19,0) PRIMARY KEY,
  name		VARCHAR2(512), 
  apptag VARCHAR(512)
);

CREATE SEQUENCE JOBINSTANCEDATA_SEQ
	START WITH 1
 	INCREMENT BY 1
 	NOMAXVALUE;


CREATE TABLE EXECUTIONINSTANCEDATA(
  jobexecid			NUMBER(19,0) PRIMARY KEY,
  jobinstanceid	NUMBER(19,0),
  createtime	TIMESTAMP,
  starttime		TIMESTAMP,
  endtime		TIMESTAMP,
  updatetime	TIMESTAMP,
  parameters	BLOB,
  batchstatus		VARCHAR2(512),
  exitstatus		VARCHAR2(512),
  CONSTRAINT JOBINST_JOBEXEC_FK FOREIGN KEY (jobinstanceid) REFERENCES JOBINSTANCEDATA (jobinstanceid)
);

CREATE SEQUENCE EXECINSTANCEDATA_SEQ
	START WITH 1
 	INCREMENT BY 1
 	NOMAXVALUE;



CREATE TABLE STEPEXECUTIONINSTANCEDATA(
	stepexecid			NUMBER(19,0) PRIMARY KEY,
	jobexecid	NUMBER(19,0),
	batchstatus         VARCHAR2(512),
    exitstatus			VARCHAR2(512),
    stepname			VARCHAR2(512),
	readcount			NUMBER(11, 0),
	writecount			NUMBER(11, 0),
	commitcount         NUMBER(11, 0),
	rollbackcount		NUMBER(11, 0),
	readskipcount		NUMBER(11, 0),
	processskipcount	NUMBER(11, 0),
	filtercount			NUMBER(11, 0),
	writeskipcount		NUMBER(11, 0),
	startTime           TIMESTAMP,
	endTime             TIMESTAMP,
	persistentData		BLOB,
	CONSTRAINT JOBEXEC_STEPEXEC_FK FOREIGN KEY (jobexecid) REFERENCES EXECUTIONINSTANCEDATA (jobexecid)
);

CREATE SEQUENCE STEP_SEQ
	START WITH 1
 	INCREMENT BY 1
 	NOMAXVALUE;


CREATE TABLE JOBSTATUS (
  id		NUMBER(19,0) PRIMARY KEY,
  obj		BLOB,
  CONSTRAINT JOBSTATUS_JOBINST_FK FOREIGN KEY (id) REFERENCES JOBINSTANCEDATA (jobinstanceid) ON DELETE CASCADE
);

CREATE TABLE STEPSTATUS(
  id		NUMBER(19,0) PRIMARY KEY,
  obj		BLOB,
  CONSTRAINT STEPSTATUS_STEPEXEC_FK FOREIGN KEY (id) REFERENCES STEPEXECUTIONINSTANCEDATA (stepexecid) ON DELETE CASCADE
);

CREATE TABLE CHECKPOINTDATA(
  id		VARCHAR2(512),
  obj		BLOB
);


  
