--
--
-- Licensed Materials - Property of IBM
-- 5724X98 5724Y15 5655V82 5724X99 5724Y16 5655V89 5725B69 5655W88 5725C52 5655W90 5655Y31
-- Copyright IBM Corp. 1987, 2017 All Rights Reserved
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.
--
--
DROP TABLE XOM_LIBRARY_VALUES;
DROP TABLE XOM_RESOURCES;
DROP TABLE XOM_LIBRARIES;

CREATE TABLE XOM_LIBRARIES (
  ID SERIAL8,
  NAME VARCHAR(256) NOT NULL,
  MAJOR_VERSION INT4 NOT NULL,
  MINOR_VERSION INT4 NOT NULL,
  CREATION_DATE INT8 NOT NULL,
  CONSTRAINT XL_PK PRIMARY KEY (ID),
  CONSTRAINT XL_UNIQUE UNIQUE (NAME, MAJOR_VERSION, MINOR_VERSION)
);

CREATE TABLE XOM_RESOURCES (
  ID SERIAL8,
  NAME VARCHAR(256) NOT NULL,
  MAJOR_VERSION INT4 NOT NULL,
  MINOR_VERSION INT4 NOT NULL,
  SHA1 VARCHAR(40) NOT NULL,
  CREATION_DATE INT8 NOT NULL,
  DATA BYTEA NOT NULL,
  CONSTRAINT XR_PK PRIMARY KEY (ID),
  CONSTRAINT XR_UNIQUE1 UNIQUE (NAME, MAJOR_VERSION, MINOR_VERSION),
  CONSTRAINT XR_UNIQUE2 UNIQUE (NAME, SHA1)
);

CREATE TABLE XOM_LIBRARY_VALUES (
  ID SERIAL8,
  LIBRARY_ID INT8 NOT NULL,
  URL VARCHAR(256) NOT NULL,
  CONSTRAINT XL_VLS_PK PRIMARY KEY (ID),
  CONSTRAINT XL_VLS_UN UNIQUE (LIBRARY_ID, URL),
  CONSTRAINT XL_VLS_FK FOREIGN KEY (LIBRARY_ID)
      REFERENCES XOM_LIBRARIES (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE
);
